manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: hyhy-masa
      url-base: https://github.com/hyhy-masa
    - name: caksoylar
      url-base: https://github.com/caksoylar
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: hyhy-masa
      revision: main
    - name: zmk-rgbled-widget
      remote: caksoylar
      revision: main
    # 名前を zmk-node-free-config から urob-node-free に変更してキャッシュを回避
    - name: urob-node-free
      url: https://github.com/urob/zmk-node-free-config
      revision: main
  self:
    path: config
